
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package inteprete;

/** CUP generated class containing symbol constants. */
public class Simbolos {
  /* terminals */
  public static final int Twhile = 26;
  public static final int Tfinal = 9;
  public static final int CHAR = 63;
  public static final int mayor_que = 31;
  public static final int mod = 47;
  public static final int Tthis = 13;
  public static final int Treturn = 12;
  public static final int fantasma = 59;
  public static final int coma = 56;
  public static final int igual = 52;
  public static final int igual_que = 33;
  public static final int Tfor = 29;
  public static final int Tprivate = 6;
  public static final int tbool = 21;
  public static final int Timport = 11;
  public static final int Tvoid = 10;
  public static final int Tabstract = 7;
  public static final int Tnot = 38;
  public static final int Tand = 37;
  public static final int CAD = 65;
  public static final int llavec = 55;
  public static final int tint = 19;
  public static final int llavea = 54;
  public static final int Telse = 25;
  public static final int menor_que = 30;
  public static final int Tpublic = 4;
  public static final int ttrue = 17;
  public static final int UMENOS = 66;
  public static final int ID = 64;
  public static final int menos = 43;
  public static final int EOF = 0;
  public static final int parc = 51;
  public static final int mayor_igual = 35;
  public static final int mas = 42;
  public static final int para = 50;
  public static final int error = 1;
  public static final int Tnew = 28;
  public static final int corc = 57;
  public static final int pcoma = 53;
  public static final int tstring = 22;
  public static final int cora = 58;
  public static final int pot = 46;
  public static final int por = 44;
  public static final int Tclass = 2;
  public static final int dospuntos = 40;
  public static final int menor_igual = 34;
  public static final int printtabla = 15;
  public static final int tfalse = 18;
  public static final int xor = 39;
  public static final int incremento = 48;
  public static final int Tsuper = 14;
  public static final int Tprotected = 5;
  public static final int decremento = 49;
  public static final int diferente_que = 32;
  public static final int Tor = 36;
  public static final int Tbreak = 27;
  public static final int print = 16;
  public static final int Textends = 3;
  public static final int tdouble = 23;
  public static final int Tstatic = 8;
  public static final int div = 45;
  public static final int num = 62;
  public static final int Tif = 24;
  public static final int decimal = 61;
  public static final int interrogacion = 41;
  public static final int Tpunto = 60;
  public static final int tchar = 20;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "Tclass",
  "Textends",
  "Tpublic",
  "Tprotected",
  "Tprivate",
  "Tabstract",
  "Tstatic",
  "Tfinal",
  "Tvoid",
  "Timport",
  "Treturn",
  "Tthis",
  "Tsuper",
  "printtabla",
  "print",
  "ttrue",
  "tfalse",
  "tint",
  "tchar",
  "tbool",
  "tstring",
  "tdouble",
  "Tif",
  "Telse",
  "Twhile",
  "Tbreak",
  "Tnew",
  "Tfor",
  "menor_que",
  "mayor_que",
  "diferente_que",
  "igual_que",
  "menor_igual",
  "mayor_igual",
  "Tor",
  "Tand",
  "Tnot",
  "xor",
  "dospuntos",
  "interrogacion",
  "mas",
  "menos",
  "por",
  "div",
  "pot",
  "mod",
  "incremento",
  "decremento",
  "para",
  "parc",
  "igual",
  "pcoma",
  "llavea",
  "llavec",
  "coma",
  "corc",
  "cora",
  "fantasma",
  "Tpunto",
  "decimal",
  "num",
  "CHAR",
  "ID",
  "CAD",
  "UMENOS"
  };
}

