/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package inteprete;

import ast.AST;
import static inteprete.Inteprete.v;
import java.awt.BorderLayout;
import java.awt.Component;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import org.fife.ui.rsyntaxtextarea.RSyntaxTextArea;
import org.fife.ui.rsyntaxtextarea.SyntaxConstants;
import org.fife.ui.rtextarea.Gutter;
import org.fife.ui.rtextarea.GutterIconInfo;
import org.fife.ui.rtextarea.RTextScrollPane;

/**
 *
 * @author p_ab1
 */
public class Ventana extends javax.swing.JFrame {
    String nombreArchivo="compi";
    ArrayList<String> listaArchivos = new ArrayList();
    /**
     * Creates new form Ventana
     */
    public Ventana() {
        
        initComponents();


    }
 
    public static Ventana getVentana(){
        return v;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        Bprueba = new javax.swing.JButton();
        pestanas = new javax.swing.JTabbedPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        Consola = new javax.swing.JTextArea();
        Correr = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        crear = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        guardar = new javax.swing.JMenuItem();
        guardarComo = new javax.swing.JMenuItem();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Bprueba.setText("prueba");
        Bprueba.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BpruebaActionPerformed(evt);
            }
        });

        Consola.setColumns(20);
        Consola.setFont(new java.awt.Font("Microsoft Sans Serif", 2, 14)); // NOI18N
        Consola.setRows(5);
        Consola.setDisabledTextColor(new java.awt.Color(173, 146, 43));
        Consola.setEnabled(false);
        jScrollPane2.setViewportView(Consola);

        Correr.setText("Correr");
        Correr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CorrerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pestanas, javax.swing.GroupLayout.PREFERRED_SIZE, 722, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Bprueba)
                        .addGap(18, 18, 18)
                        .addComponent(Correr))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 434, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 20, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Bprueba)
                    .addComponent(Correr))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pestanas, javax.swing.GroupLayout.DEFAULT_SIZE, 367, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        crear.setText("Archivo");

        jMenuItem2.setText("Abrir");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        crear.add(jMenuItem2);

        jMenuItem3.setText("Cerar Pestaña");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        crear.add(jMenuItem3);

        jMenuItem1.setText("Crear");
        crear.add(jMenuItem1);

        guardar.setText("Guardar");
        crear.add(guardar);

        guardarComo.setText("Guardar Como");
        crear.add(guardarComo);

        jMenuBar1.add(crear);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BpruebaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BpruebaActionPerformed
        try {
            Consola.setText("");
            String entrada = "C:\\Users\\p_ab1\\Desktop\\entrada.txt";
            
            new Sintactico(new Lexico(new BufferedReader(new FileReader(entrada)))).parse();
            
            AST arbol = Sintactico.arbol;
            if (arbol != null) {
                arbol.ejecutar();
            }
        } catch (FileNotFoundException ex) {
            JOptionPane.showMessageDialog(null, "Error en el archivo", "Ocurrion un Error", JOptionPane.ERROR_MESSAGE);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Error en el parser\n"+ex.getMessage(), "Ocurrion un Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_BpruebaActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // Menu ABRIR
        BufferedReader reader = null;
        try {           
            JFileChooser fileChooser = new JFileChooser();
            int result = fileChooser.showOpenDialog(this);
            File selectedFile = null;
            
            if (result == JFileChooser.APPROVE_OPTION) {
                selectedFile = fileChooser.getSelectedFile();
                listaArchivos.add(nombreArchivo);
                nombreArchivo = selectedFile.getName();
            }  
            
            reader = new BufferedReader(new FileReader(selectedFile.getAbsolutePath()));
            String line;
            String todo="";
            while ((line = reader.readLine()) != null)
            {
                todo = todo + line + "\n";
            }   
            reader.close();
            
            pestanas.add(nombreArchivo,agregarArchivo(todo));
            
        } catch (FileNotFoundException ex) {
            JOptionPane.showMessageDialog(null, "No Encontro el Archivo FileNotFoundException", "Error en Archivo", JOptionPane.ERROR_MESSAGE);
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(null, "No Encontro el Archivo IOException", "Error en Archivo", JOptionPane.ERROR_MESSAGE);
        } finally {
            try {
                reader.close();
            } catch (IOException ex) {
                JOptionPane.showMessageDialog(null, "No Encontro el Archivo IOException 2", "Error en Archivo", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void CorrerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CorrerActionPerformed
        
            // TODO add your handling code here:
            String txt;
        try {  
            int select = pestanas.getSelectedIndex();
            Component com = pestanas.getSelectedComponent();
            JPanel panel = (JPanel)com;
            RTextScrollPane rt = (RTextScrollPane) panel.getComponent(0);
            RSyntaxTextArea rs = (RSyntaxTextArea) rt.getTextArea();
            txt = rs.getText();
            FileWriter fw = new FileWriter("entrada.txt");
            fw.write(txt);
            fw.close();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error en Casteo Visual\n"+e.getMessage(), "Ocurrion un Error", JOptionPane.ERROR_MESSAGE);        
        }
        
        try {    
            //new Sintactico(new Lexico(new BufferedReader(new FileReader(txt)))).parse();
            new Sintactico(new Lexico(new BufferedReader(new FileReader("entrada.txt")))).parse();
            AST arbol = Sintactico.arbol;
            if (arbol != null) {
                arbol.ejecutar();
            }        
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Error en el parser\n"+ex.getMessage(), "Ocurrion un Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_CorrerActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        if (pestanas.getTabCount() != 0 || listaArchivos.size() != 0 ) {
            pestanas.remove(pestanas.getTabCount()-1);
            listaArchivos.remove(listaArchivos.size() - 1);
        }
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Bprueba;
    private javax.swing.JTextArea Consola;
    private javax.swing.JButton Correr;
    private javax.swing.JMenu crear;
    private javax.swing.JMenuItem guardar;
    private javax.swing.JMenuItem guardarComo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane pestanas;
    // End of variables declaration//GEN-END:variables

       
    private JPanel agregarArchivo(String texto){
        JPanel cp = new JPanel(new BorderLayout());
        RTextScrollPane sp = new RTextScrollPane(createTextArea(texto));
        sp.setFoldIndicatorEnabled(true);
        sp.setIconRowHeaderEnabled(true);
        sp.setLineNumbersEnabled(true);
        cp.add(sp);
        return cp;
    }
    
    private RSyntaxTextArea createTextArea(String texto) {
	RSyntaxTextArea textArea = new RSyntaxTextArea(25, 70);
        textArea.setSyntaxEditingStyle(SyntaxConstants.SYNTAX_STYLE_JAVA);
        textArea.setCodeFoldingEnabled(true);
	textArea.setTabSize(3);
        textArea.setText(texto);
	textArea.setCaretPosition(0);
	textArea.requestFocusInWindow();
	textArea.setMarkOccurrences(true);
	textArea.setCodeFoldingEnabled(true);
	textArea.setClearWhitespaceLinesEnabled(true);
	textArea.setAntiAliasingEnabled(true);
	textArea.setLineWrap(true);
        textArea.setFadeCurrentLineHighlight(true);
	return textArea;
    }
            
    public void agregarConsola(String cad){
        Consola.setText(Consola.getText()+""+ cad);
    }
    
    public void agregarConsolaln(String cad){
        Consola.setText(Consola.getText()+""+ cad + "\n");
    }
}
